# 站点设置
title: 守心向暖 - 以最烟火的平淡守心向暖
description: 恒心是成功最好的帮手，不要妄自菲薄，也不要觉得每天一点点的进步微不足道。
permalink: /:year/:month/:day/:title/
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: umiyo
user_description: 竹杖芒鞋轻胜马，一蓑烟雨任平生。
user_title: 前端开发工程师
email: znyaiw@163.com
github_username: umiyo

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil

# 分页设置
paginate: 10
paginate_path: "page/:num"

exclude: ['package.json', 'src' , 'node_modules']
